openapi: 3.1.0
info:
  title: Yoga-Studio Relite
  description: "Die Yoga-Studio-App nutzt einen simplen REST-Webservices zur Kommunikation\
    \ mit dem Backend. Dieser ermöglicht die üblichen CRUD-Operationen zur Suche,\
    \ Anzeige, Bearbeitung und Löschung von Anmeldungen bei Yoga-Kursen, wobei jede Yoga-Kurs-Anmeldung aus einem\
    \ Vornamen, Nachnamen und einer Mitgliedsnummer besteht."
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:80080
tags:
- name: Index
- name: YogaKurs
paths:
  /:
    get:
      tags:
      - Index
      summary: Wurzeladresse des Webservices
      description: Liefert eine HATEOAS-Übersicht aller collections
      operationId: index
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json

  /Yoga-Kurs:
    get:
      tags:
      - YogaKurs
      summary: Yoga-Kurs-Teilnehmer suchen
      description: Suche nach Teilnehmer des Yoga-Kurses. Gibt eine Liste aller Teilnehmer passend zu
        den übergebenen Suchkriterien zurück.
      operationId: search-yogakurs
      parameters:
      - name: first_name
        in: query
        description: Gesuchter Vorname
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: last_name
        in: query
        description: Gesuchter Nachname
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: mitgliedsnummer
        in: query
        description: Gesuchte Mitgliedsnummer
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Yoga-Kurs'
                x-content-type: application/json
    post:
      tags:
      - YogaKurs
      summary: Zum Yoga-Kurs anmelden
      description: "Neue Anmeldung eines Kursteilnehmers. Speichert die übergebene Anmeldung in der\
        \ Datenbank. Der Wert des Feldes \"_id\" wird dabei ignoriert, da in jedem Fall\
        \ eine neue Anmeldung mit neuer ID angelegt wird."
      operationId: create-anmeldung
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YogaKurs'
      responses:
        "201":
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YogaKurs'

  /YogaKurs/{id}:
    get:
      tags:
      - YogaKurs
      summary: Yoga-Kurs-Anmeldung lesen
      description: Liest eine einzelnen Yoga-Kurs-Anmeldung vom Server.
      operationId: get-anmeldung
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YogaKurs'
        "404":
          description: Not Found
    put:
      tags:
      - Anmeldung überschreiben
      summary: ""
      description: "Überschreibt eine vorhandene Anmeldung auf dem Server. Bis auf die\
        \ ID können alle Felder geändert werden. Der Versuch, die ID zu ändern, wird\
        \ vom Server stillschweigend ignoriert."
      operationId: update-anmeldung
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YogaKurs'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YogaKurs'
        "404":
          description: Not Found
    patch:
      tags:
      - Einzelne Felder ändern
      summary: Einzelne Yoga-Kurs-Anmeldungsfelder ändern
      description: "Ändert einzelne Felder einer vorhandenen Anmeldung. Zulässig sind\
        \ alle Felder bis auf die ID, da diese nachträglich nicht mehr verändert werden\
        \ darf."
      operationId: patch-anmeldung
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YogaKurs'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YogaKurs'
        "404":
          description: Not Found
    delete:
      tags:
      - YogaKurs
      summary: Anmeldung löschen
      description: Löscht eine Anmeldung auf dem Server.
      operationId: delete-anmeldung
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found

components:
  schemas:
    HATEOAS_Collection:
      title: HATEOAS-Links einer Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Resource:
      title: HATEOAS-Links einer Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Link:
      title: HATEOAS-Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string

    YogaKurs:
      title: YogaKurs
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HATEOAS_Resource'
        _id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        mitlgiedsnummer:
          type: string
      required:
        - first_name
        - last_name
      example:
        _id: "621ff9a936997df5baba746e"
        first_name: "Fox"
        last_name: "Mulder"
        mitgliedsnummer: "5462"

  securitySchemes: {}
